-- AlterTable
ALTER TABLE "Contact" ADD COLUMN     "sourceId" BIGINT;

-- CreateTable
CREATE TABLE "hl_contacts" (
    "id" BIGINT NOT NULL,
    "business_id" INTEGER,
    "contactid" TEXT,
    "full_name" TEXT,
    "email" TEXT,
    "phone" TEXT,
    "tag" TEXT,
    "note" TEXT,
    "campaign" TEXT,
    "utm_medium" TEXT,
    "utm_content" TEXT,
    "createdat" TIMESTAMPTZ,
    "utm_term" TEXT,
    "lastsubdate" TIMESTAMPTZ,
    "dateupdated" TIMESTAMPTZ,
    "url" TEXT,
    "funnel_id" TEXT,
    "page_id" TEXT,
    "step_id" TEXT,
    "utm_source" TEXT,
    "date_closed" TIMESTAMPTZ,
    "self_app_date" TIMESTAMPTZ,
    "app_date" TIMESTAMPTZ,
    "calendar_type" TEXT,
    "app_campaign" TEXT,
    "app_utm_medium" TEXT,
    "app_utm_content" TEXT,
    "formid" TEXT,
    "calendarid" TEXT,
    "campaign_id" TEXT,
    "ad_id" TEXT,
    "is_spam" BOOLEAN,
    "tenant_id" INTEGER,
    "notes" TEXT,
    "tags" TEXT,
    "address1" TEXT,
    "city" TEXT,
    "state" TEXT,
    "postal_code" TEXT,
    "country" TEXT,
    "email_hash" TEXT,
    "phone_hash" TEXT,
    "ad_platform" TEXT,
    "first_url" TEXT,
    "crm_provider" TEXT,
    "match_method" TEXT,
    "fbclid" TEXT,
    "fbc" TEXT,
    "fbp" TEXT,
    "email_norm" TEXT,
    "phone_norm" TEXT,
    "identity_norm_at" TIMESTAMPTZ,
    "lead_source" TEXT,
    "lead_sources" TEXT,

    CONSTRAINT "hl_contacts_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "Contact_sourceId_idx" ON "Contact"("sourceId");
